import Head from 'next/head'
import styles from '@/styles/index.module.scss'
import { Button, Dialog, Toast, TextArea, ImageUploader } from 'antd-mobile'
import axios from 'axios'
import { useState } from 'react'
export default function Home() {
  const [username, setUsername] = useState('')
  const [email, setEmail] = useState('')
  const [remark, setRemark] = useState('')
  const [imgUrl, setImgUrl] = useState('')


  const upload = async (res:any) => {
    // console.log(res)
    const data = new FormData();
    data.append('file', res);
    const response = await axios({
      url: '/api/active/upload',
      method: 'post',
      data
    });
    // console.log(response,`https://www.nfcmdx.top/api/${response.data.url}`)
    setImgUrl(response.data.url);
    return {
      url: `https://www.nfcmdx.top/api${response.data.url}`
    }
  }
  const submitInfo = () => {
    // console.log(email,username,remark)
    if(!username||!email||!imgUrl||!remark){
      Dialog.alert({
        content: "全部内容都要填写哦，检查一下吧！"
      })
      return 
    }
    Dialog.confirm({
      content: '上传的内容不得包含色情，反动等违反国家法律的内容，我们将对您上传的内容进行严格审核，确认提交吗？',
      onConfirm: async () => {
        await axios({
          method: 'post',
          url: '/api/active/add',
          data: {
            listen: email,
            name: username,
            image_url: imgUrl,
            remark
          }
        })
        Toast.show({
          icon: 'success',
          content: '提交成功',
          position: 'bottom',
        })
      },
    })
    
  }
  return (
    <>
      <Head>
        <title>五月的纪念-致未来</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <form className={styles.form}>
          <input onChange={({ target: { value } }) => { setUsername(value) }} type="text" id="name" name="name" placeholder="请输入你的昵称" />
          <input onChange={({ target: { value } }) => { setEmail(value) }} id="email" name="email" placeholder="请输入你的联系方式，例如：微信：xxxxxx" />
          <TextArea onChange={(value) => { setRemark(value) }} placeholder="请输入对这张照片的简单描述" />
          <ImageUploader maxCount={1} upload={upload} />
          <Button block onClick={submitInfo} color='primary' size='large'>提交</Button>
        </form>
      </div>
    </>
  )
}
